/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cowj;

import org.junit.Assert;
import org.junit.Test;

public class ModelTest {

    @Test
    public void loadingTest(){
        final String p = "samples/hello/hello.yaml" ;
        Model m = Model.from(p);
        Assert.assertNotNull(m);
        Assert.assertFalse(m.routes().isEmpty());
        Assert.assertFalse(m.threading().isEmpty());
        Assert.assertFalse(m.filters().isEmpty());
        Assert.assertFalse(m.dataSources().isEmpty());
        Assert.assertEquals( 1003, m.port());
    }
}
