/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cowj;

public class App {
    public static void main(String[] args) {
        if ( args.length < 1 ){
            System.out.println("Usage : java -jar cowj.jar <config_file_path>");
            return;
        }
        final String path = args[0];
        ModelRunner mr = ModelRunner.fromModel(path) ;
        mr.run();
    }
}
