#####################
# Defines the Schemas for routes
# https://json-schema.org/learn/miscellaneous-examples.html
#####################
labels:
  ok:  "resp.status == 200"
  err:  "resp.status != 200"

verify:
  in: true
  out: true

routes:
  /users:
    get:
      params: params.json # this defines parameters
      ok: output.json

  /u2:
    get:
      params: params.json # this defines parameters
      ok: output.json

  /person:
      post:
        in: Person.json
        ok: RetVal.json
        err: RetVal.json
  /invalid:
    post:
      in: Person.json
      ok: RetVal.json
      err: RetVal.json

  /person/*:
    get:
      ok: Person.json
      err: RetVal.json

storages:
  in-mem-storage:
    read: true # just for the heck of it
    sep: "/" # default sep is also same
    paths:
      ".*" : Person.json # all storage path matches to this schema

