#########################
# Schema validation test bed
# Also, using _shared
#########################

port: 5042

# threading related stuff
threading:
  min: 4
  max : 8
  timeout: 30000

# path mapping
routes:
  post:
    /person: _/create_person.zm
    /invalid: _/invalid.zm

  get:
    /person/:personId : _/fetch_person.zm

proxies:
  get:
    /users: json_place/users
    /u2: json_place/users

filters:
  finally:
    /users: _/after.zm

plugins:
  cowj.plugins:
    curl: CurlWrapper::CURL
    mem-st: MemoryBackedStorage::STORAGE

data-sources:
  json_place:
    type: curl
    url: https://jsonplaceholder.typicode.com

  in-mem-storage:
    type: mem-st


cron:
  r:
    exec: _/cron.zm
    boot: true
    at: "0/30 * * * * ? *"
    # https://stackoverflow.com/questions/35214149/cron-expression-for-every-30-seconds-in-quartz-scheduler
